mysql_version: "5.7.28"
mysql_config_file: "my.cnf_5.7.j2"

dba: "root"
dba_pass: "your_password"

app_db_name: "app_db"
app_db_users:
  - name: "app"
    password: "your_password"
    priv: "{{ app_db_name }}.*:ALL"
    host: "%"
