# Install Nginx packages
- name: Install nginx packages
  yum:
    name: "nginx"
    state: present
    enablerepo: ultra-centos-7.x-epel


# Add custom index page
- name: Insert index page
  template:
    src: index.html.j2
    dest: /usr/share/nginx/html/index.html


# Start nginx server
- name: Start nginx server
  service:
    name: nginx
    state: started
    enabled: yes

